# Generated by Django 5.2.6 on 2026-03-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_user_role_groupcombinedsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsproduct',
            name='product_type',
            field=models.CharField(choices=[('regular', 'Regular Savings'), ('fixed', 'Fixed Deposit'), ('target', 'Voluntary Savings'), ('children', 'Children Savings')], db_index=True, default='regular', help_text='Type of savings product - determines ALL account behavior', max_length=20),
        ),
    ]
