# Generated by Django 5.2.6 on 2026-03-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_savingsproduct_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='loan_type',
            field=models.CharField(choices=[('regular', 'Regular Loan'), ('special', 'Special Loan'), ('med', 'Med Loan'), ('asset', 'Asset Loan'), ('thrift', 'Thrift Loan'), ('midterm', 'Midterm Loan'), ('golden', 'Golden Loan')], db_index=True, help_text='Type of loan product', max_length=20),
        ),
    ]
