# Generated by Django 5.2.6 on 2026-03-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_loanproduct_loan_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_active_client_email',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('email__isnull', False)), fields=('email',), name='unique_active_client_email'),
        ),
    ]
