# Generated by Django 5.2.6 on 2026-03-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_make_client_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='approval_date',
            field=models.DateField(blank=True, help_text='Official approval date entered by the approving manager/director', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_date',
            field=models.DateField(blank=True, help_text='Date the client was physically registered (entered by staff)', null=True),
        ),
    ]
