# Generated by Django 5.2.6 on 2026-03-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_client_registration_and_approval_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activation_date',
            field=models.DateField(blank=True, help_text='Date the client account was activated, entered by the activating officer', null=True),
        ),
    ]
