# Generated by Django 5.2.6 on 2026-03-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_client_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsproduct',
            name='product_type',
            field=models.CharField(choices=[('regular', 'Regular Savings'), ('fixed', 'Fixed Deposit'), ('target', 'Voluntary Savings'), ('children', 'Children Savings'), ('thrift', 'Thrift Savings')], db_index=True, default='regular', help_text='Type of savings product - determines ALL account behavior', max_length=20),
        ),
    ]
