# Generated by Django 5.2.6 on 2026-03-20 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_thrift_savings_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='approval_date',
            field=models.DateField(blank=True, help_text='Official date the account was approved (entered by the approver)', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='application_date',
            field=models.DateField(default=datetime.date.today, help_text='Date the loan application was submitted'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approval_date',
            field=models.DateField(blank=True, help_text='Official date the loan was approved or rejected', null=True),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='date_opened',
            field=models.DateField(default=datetime.date.today, help_text='Date account was opened (editable — defaults to today)'),
        ),
    ]
