# Generated by Django 5.2.6 on 2026-03-30 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_editable_dates_savings_and_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='max_client_age',
            field=models.IntegerField(default=120, validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
