# Generated by Django 5.2.6 on 2026-03-30 11:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_increase_max_client_age_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_maintenance_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='loan_maintenance_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='loan_maintenance_fee_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
