# Generated by Django 5.2.6 on 2026-06-22 05:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_loan_cancelled_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Savings Deposit'), ('withdrawal', 'Savings Withdrawal'), ('interest_credit', 'Interest Credit'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('interest_applied', 'Interest Applied'), ('charges_at_disbursement', 'Charges At Disbursement'), ('registration_fee', 'Client Registration Fee'), ('id_card_fee', 'ID Card Fee'), ('membership_card_fee', 'Membership Card Fee'), ('loan_insurance_fee', 'Loan Insurance Fee'), ('loan_form_fee', 'Loan Form Fee'), ('risk_premium', 'Risk Premium Fee'), ('rp_income', 'RP Income Fee'), ('tech_fee', 'Technology Fee'), ('fee', 'Fee / Charge'), ('group_savings_deposit', 'Group Savings Deposit'), ('reversal', 'Reversal'), ('transfer', 'Transfer')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='GroupSavingsAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null = not deleted)', null=True)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this record was approved', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('account_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_savings_accounts', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_savings_accounts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_savings_accounts', to='core.clientgroup')),
                ('savings_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_savings_accounts', to='core.savingsproduct')),
            ],
            options={
                'verbose_name': 'Group Savings Account',
                'verbose_name_plural': 'Group Savings Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='group_savings_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.groupsavingsaccount'),
        ),
        migrations.CreateModel(
            name='GroupSavingsPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null = not deleted)', null=True)),
                ('posting_ref', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('collection_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_group_savings_postings', to=settings.AUTH_USER_MODEL)),
                ('group_savings_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='core.groupsavingsaccount')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_group_savings_postings', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_group_savings_postings', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_savings_posting', to='core.transaction')),
            ],
            options={
                'verbose_name': 'Group Savings Posting',
                'verbose_name_plural': 'Group Savings Postings',
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupSavingsPostingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null = not deleted)', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_savings_posting_items', to='core.client')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.groupsavingsposting')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='groupsavingsaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='group_savings_account_balance_positive'),
        ),
    ]
