# Generated by Django 5.2.6 on 2026-06-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_group_savings_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsproduct',
            name='product_type',
            field=models.CharField(choices=[('regular', 'Regular Savings'), ('fixed', 'Fixed Deposit'), ('target', 'Voluntary Savings'), ('children', 'Children Savings'), ('thrift', 'Thrift Savings'), ('group_savings', 'Group Savings')], db_index=True, default='regular', help_text='Type of savings product - determines ALL account behavior', max_length=20),
        ),
    ]
