# Generated by Django 5.2.6 on 2026-06-22 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_seed_group_savings_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Savings Deposit'), ('withdrawal', 'Savings Withdrawal'), ('interest_credit', 'Interest Credit'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('interest_applied', 'Interest Applied'), ('charges_at_disbursement', 'Charges At Disbursement'), ('registration_fee', 'Client Registration Fee'), ('id_card_fee', 'ID Card Fee'), ('membership_card_fee', 'Membership Card Fee'), ('loan_insurance_fee', 'Loan Insurance Fee'), ('loan_form_fee', 'Loan Form Fee'), ('risk_premium', 'Risk Premium Fee'), ('rp_income', 'RP Income Fee'), ('tech_fee', 'Technology Fee'), ('fee', 'Fee / Charge'), ('group_savings_deposit', 'Group Savings Deposit'), ('group_savings_withdrawal', 'Group Savings Withdrawal'), ('reversal', 'Reversal'), ('transfer', 'Transfer')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='GroupSavingsWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null = not deleted)', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('withdrawal_date', models.DateField()),
                ('purpose', models.CharField(help_text='What is this withdrawal for?', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('withdrawal_ref', models.CharField(editable=False, max_length=30, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_group_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('group_savings_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='core.groupsavingsaccount')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_group_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_group_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_savings_withdrawal_posting', to='core.transaction')),
            ],
            options={
                'ordering': ['-withdrawal_date', '-created_at'],
            },
        ),
    ]
