# Generated by Django 5.2.6 on 2026-08-03 05:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='admin_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('2500.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='admin_fee_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
