# Generated by Django 5.2.6 on 2026-08-29 05:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_admin_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null = not deleted)', null=True)),
                ('purpose', models.CharField(choices=[('due_reminder', 'Repayment Due Reminder'), ('overdue_alert', 'Overdue Alert'), ('manual', 'Manual / On-demand')], default='due_reminder', max_length=20)),
                ('phone', models.CharField(help_text='Number the call was placed to', max_length=20)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('message_text', models.TextField(help_text='Script read to the client in the AI voice')),
                ('audio_url', models.URLField(blank=True, help_text='Hosted TTS audio played on the call')),
                ('call_sid', models.CharField(blank=True, db_index=True, help_text='Twilio Call SID', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('busy', 'Busy'), ('failed', 'Failed'), ('no-answer', 'No Answer'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_call_logs', to='core.client')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='Staff user who triggered a manual call; blank for scheduled reminders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls_initiated', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_call_logs', to='core.loan')),
                ('schedule_row', models.ForeignKey(blank=True, help_text='Installment this reminder call was about, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_call_logs', to='core.loanrepaymentschedule')),
            ],
            options={
                'verbose_name': 'Voice Call Log',
                'verbose_name_plural': 'Voice Call Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='core_voicec_client__22cc6f_idx'), models.Index(fields=['loan', 'created_at'], name='core_voicec_loan_id_a5db83_idx'), models.Index(fields=['status'], name='core_voicec_status_a051a8_idx'), models.Index(fields=['call_sid'], name='core_voicec_call_si_1eab35_idx')],
            },
        ),
    ]
