# Generated by Django 5.2.6 on 2026-09-07 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_voicecalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deceased_date',
            field=models.DateField(blank=True, help_text='Date of death, if known', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_deceased',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='marked_deceased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='marked_deceased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_marked_deceased', to=settings.AUTH_USER_MODEL),
        ),
    ]
