# Generated by Django 5.2.6 on 2026-09-27 01:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_client_deceased_date_client_is_deceased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='admin_fee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0270'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
    ]
