# Generated by Django 5.2.6 on 2026-09-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_loanproduct_admin_fee_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('staff', 'Staff/Loan Officer'), ('manager', 'Branch Manager'), ('director', 'Director'), ('hr', 'Human Resources Manager'), ('admin', 'System Administrator'), ('auditor', 'Auditor (Read-Only)')], db_index=True, max_length=20),
        ),
    ]
